// src/components/admin/ManualContentPanel.jsx
// Backup entry: admin pastes content generated by an external AI engine
// (used when Base44 AI tokens are exhausted). Saves as draft; publishing is still required.

import React, { useState } from "react";
import { base44 } from "@/api/base44Client";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { ClipboardPaste, Loader2, CheckCircle2 } from "lucide-react";

const MANUAL_TYPES = [
  {
    key: "lesson_notes",
    label: "Nota Pelajaran (Markdown)",
    placeholder: "# Tajuk Pelajaran\n\n## Matlamat Pembelajaran\n...\n\n## Penjelasan Konsep\n...",
    format: "markdown",
  },
  {
    key: "infographic",
    label: "Infografik (Markdown / URL Gambar)",
    placeholder: "# Ringkasan Pelajaran\n\n- Fakta 1\n- Fakta 2\n\nURL gambar: https://...",
    format: "markdown",
  },
  {
    key: "mindmap",
    label: "Peta Minda (JSON branches)",
    placeholder: '[{"label":"Cabang 1","children":["Anak 1","Anak 2"]},{"label":"Cabang 2","children":["Anak 3"]}]',
    format: "json",
  },
  {
    key: "flashcards",
    label: "Flashcards (JSON array)",
    placeholder: '[{"front":"Soalan?","back":"Jawapan","explanation":"Penerangan tambahan"}]',
    format: "json",
  },
  {
    key: "questions",
    label: "Soalan Kuiz (JSON array)",
    placeholder: '[{"question":"...","options":["A","B","C","D"],"correct_answer":"A","explanation":"...","difficulty":"easy"}]',
    format: "json",
  },
  {
    key: "worksheet",
    label: "Lembaran Kerja (Markdown)",
    placeholder: "Kandungan lembaran kerja dalam format Markdown...",
    format: "markdown",
  },
];

export default function ManualContentPanel({ lessonVersionId, onSaveComplete }) {
  const [selectedType, setSelectedType] = useState("lesson_notes");
  const [rawContent, setRawContent] = useState("");
  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);

  const typeInfo = MANUAL_TYPES.find((t) => t.key === selectedType);

  const handleSave = async () => {
    if (!rawContent.trim()) return;
    setSaving(true);
    setSaved(false);
    try {
      const lv = await base44.entities.LessonVersion.get(lessonVersionId);
      const lessonId = lv.lesson_id;
      const common = { created_source: "manual" };
      const sortOrders = { lesson_notes: 0, worksheet: 2, mindmap: 3, infographic: 4 };

      if (["lesson_notes", "infographic", "mindmap", "worksheet"].includes(selectedType)) {
        const titles = {
          lesson_notes: "Nota Pelajaran (Manual)",
          infographic: "Infografik (Manual)",
          mindmap: "Peta Minda (Manual)",
          worksheet: "Lembaran Kerja (Manual)",
        };
        await base44.entities.LessonContent.create({
          lesson_version_id: lessonVersionId,
          content_type: selectedType === "lesson_notes" ? "notes" : selectedType,
          title: titles[selectedType],
          content_markdown: rawContent,
          sort_order: sortOrders[selectedType] ?? 0,
          status: "draft",
          ...common,
        });
      } else if (selectedType === "flashcards") {
        const cards = JSON.parse(rawContent);
        if (!Array.isArray(cards)) throw new Error("Format mesti array JSON.");
        await base44.entities.Flashcard.bulkCreate(
          cards.map((fc, i) => ({
            lesson_id: lessonId,
            lesson_version_id: lessonVersionId,
            front: fc.front || "",
            back: fc.back || "",
            front_text: fc.front || "",
            back_text: fc.back || "",
            explanation: fc.explanation || "",
            sort_order: i,
            ...common,
          }))
        );
      } else if (selectedType === "questions") {
        const questions = JSON.parse(rawContent);
        if (!Array.isArray(questions)) throw new Error("Format mesti array JSON.");
        await base44.entities.QuestionBank.bulkCreate(
          questions.map((q, i) => ({
            lesson_id: lessonId,
            lesson_version_id: lessonVersionId,
            question_id: `manual_${Date.now()}_${i}`,
            question: q.question || "",
            correct_answer: q.correct_answer || "",
            explanation: q.explanation || "",
            difficulty: q.difficulty || "medium",
            quiz_type: "practice",
            question_type: "mcq",
            options_json: JSON.stringify(q.options || []),
            hint: q.hint || "",
            cognitive_level: q.cognitive_level || "understand",
            status: "draft",
            ...common,
          }))
        );
      }

      setSaved(true);
      setRawContent("");
      setTimeout(() => setSaved(false), 2500);
      onSaveComplete?.();
    } catch (e) {
      alert("Gagal menyimpan: " + (e.message || "ralat. Semak format JSON."));
    } finally {
      setSaving(false);
    }
  };

  return (
    <div className="space-y-4">
      <div className="flex items-center gap-2 text-sm font-heading font-bold text-primary">
        <ClipboardPaste className="w-4 h-4" /> Tampal Kandungan dari AI Luar
      </div>
      <p className="text-xs text-muted-foreground">
        Backup apabila token AI Base44 telah habis. Tampal output dari enjin AI lain (ChatGPT, Gemini, dsb).
        Semua kandungan disimpan sebagai <strong>draft</strong> — perlu diterbitkan sebelum pelajar nampak.
      </p>

      <div className="space-y-2">
        <Label className="text-xs">Jenis Kandungan</Label>
        <div className="flex flex-wrap gap-2">
          {MANUAL_TYPES.map((t) => (
            <button
              key={t.key}
              onClick={() => { setSelectedType(t.key); setRawContent(""); }}
              className={`text-xs px-3 py-1.5 rounded-full border transition-colors ${selectedType === t.key ? "bg-primary text-primary-foreground border-primary" : "bg-background border-border hover:bg-accent"}`}
            >
              {t.label}
            </button>
          ))}
        </div>
      </div>

      <div className="space-y-2">
        <Label className="text-xs">
          Kandungan {typeInfo.format === "json" ? "(format JSON)" : "(format Markdown)"}
        </Label>
        <Textarea
          value={rawContent}
          onChange={(e) => setRawContent(e.target.value)}
          placeholder={typeInfo.placeholder}
          rows={10}
          className="font-mono text-xs"
        />
      </div>

      <Button onClick={handleSave} disabled={saving || !rawContent.trim()} size="sm">
        {saving ? <Loader2 className="w-4 h-4 animate-spin mr-1" /> : saved ? <CheckCircle2 className="w-4 h-4 mr-1 text-emerald-500" /> : <ClipboardPaste className="w-4 h-4 mr-1" />}
        {saving ? "Menyimpan..." : saved ? "Disimpan sebagai Draft" : "Simpan sebagai Draft"}
      </Button>
    </div>
  );
}